language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
env:
    - DJANGO_PACKAGE="Django>=1.5,<1.6"
    - DJANGO_PACKAGE=git+git://github.com/django/django.git
install: pip install $DJANGO_PACKAGE --use-mirrors
script: python setup.py test
